### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by yasinabdmahmood** [yasinabdmahmood/Recipe-app#17]
the link to the kanban board is [here](https://github.com/yasinabdmahmood/Recipe-app/projects/1)

# collaborators
- [yaseen](https://github.com/yasinabdmahmood)
- [Benjamin](https://github.com/iambenkis)

**Comment by sumairq** [comment]
### Hi Team , 

<img src="https://media1.giphy.com/media/iemmYj32EiEeZYvjpq/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Issues are correctly assigned to team members.
✔️ Each requirement has at least one corresponding card.
✔️All the required columns are present

## Required Changes ♻️
- [ ] Two of the issues are not assigned number of points. Kindly assign the number of points to the remaing two issues. Please refer to issue #16  and #5  
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cynthiainga** [comment]
Hi @yasinabdmahmood & @iambenkis, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] All cards are correctly assigned ✔️ 
- [ ] All the required columns are present ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
